### ISSUE TITLE
Wechat类里面 写法问题；对象当数组用，到php7里面全部报错，能否更新下？

### ISSUE THREAD

**Issue by laojiu** [luweiss/wechat#1]
$target = !empty($this->cache['target']) ? $this->cache['target'] : static::CACHE_TARGET_FILE;

**Comment by laojiu** [comment]
最近做了个小程序的项目，用的你的库 ，哈哈

**Comment by luweiwei** [comment]
你好，这个问题已得到修复，感谢支持！

**Comment by luweiwei** [comment]
你好，这个问题已得到修复，感谢支持！

**Comment by luweiwei** [comment]
> $target = !empty($this->cache['target']) ? $this->cache['target'] : static::CACHE_TARGET_FILE;

你好，这个问题已得到修复，感谢支持！
